---
- name: update the server
  apt:
    update_cache: yes

- name: ensure tomcat is at the latest version
  apt:
    name: tomcat7
    state: latest

- name: Change owner of Tomcat installation
  file:
    path: /usr/share/tomcat7/
    owner: tomcat7
    group: tomcat7
    state: directory
    recurse: yes

