---
- hosts: all
  sudo: yes

  tasks:

  - name: update the server
    apt:
      update_cache: yes

  - name: install Node
    apt:
      name: nodejs
      state: present

  - name: install Node legacy
    apt:
      name: nodejs-legacy
      state: present

  - name: install npm
    apt:
      name: npm
      state: present

  - name: install
    apt:
      name: libfontconfig
      state: present

  - name: install dependencies
    npm: path=/opt/software/tdd-js

  - name: run tests
    command: grunt test
    register: test_output
    args:
      chdir: /opt/software/tdd-js

  - debug: var=test_output.stdout_lines
